---
- name: Install elasticsearch packages
  ansible.builtin.import_tasks: install.yml

- name: Configure certs
  ansible.builtin.import_tasks: certs.yml

- name: Setup configuration
  ansible.builtin.import_tasks: config.yml

- name: Start the cluster
  ansible.builtin.import_tasks: service.yml
